cars:
  count: 150000
  arrival_time_min: 1ms   # new car arrives every 1-2ms
  arrival_time_max: 2ms
  line_capacity: 8
stations:
  gas:
    count: 3
    line_capacity: 2
    serve_time_min: 2ms
    serve_time_max: 5ms
  diesel:
    count: 3
    line_capacity: 2
    serve_time_min: 3ms
    serve_time_max: 6ms
  lpg:
    count: 2
    line_capacity: 2
    serve_time_min: 4ms
    serve_time_max: 7ms
  electric:
    count: 2
    line_capacity: 2
    serve_time_min: 5ms
    serve_time_max: 10ms
registers:
  count: 4
  line_capacity: 5
  handle_time_min: 1ms
  handle_time_max: 3ms
